package ar.edu.itba.pod.legajo49015.message;

public enum MessageType {
	ADD_SIGNAL, ADD_FINISHED,
	REMOVE_BACKUP_SIGNAL, ADD_BACKUP_SIGNAL, 
	ASK_INITIAL_SIGNALS,
	COMPARE_SIGNAL, COMPARE_RESULTS,
	DEGRADE_MODE, NORMAL_MODE, 
	REORDERING_FINISHED
}
